language: c
compiler:
    - gcc
    - clang

before_install:
    - |
      if [ "$CC" = "gcc" ]; then
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        export CC="gcc-4.8"
      fi
    - sudo apt-get update -qq
    - sudo apt-get build-dep -qq irssi
    - sudo apt-get install -qq lynx
    - |
      case "$CC" in gcc-*) :
        sudo apt-get install -qq $CC
      esac

script:
    - ./autogen.sh --with-proxy --with-bot
    - cat config.log
    - make
    - sudo make install

notifications:
    irc:
        channels:
            - "irc.freenode.net#irssi"
        template:
            - "%{repository} (%{commit}: %{author}): %{message}"
            - "Build details : %{build_url}"
        on_success: always
        on_failure: always
        use_notice: true
        skip_join: true
